### ISSUE TITLE
Request: Docker Image

### ISSUE THREAD

**Issue by markv** [philippbosch/slack-webhook-cli#3]
@philippbosch - It would be great to have a docker image of this tool up on https://hub.docker.com

**Comment by philippbosch** [comment]
Ok, I created one: https://hub.docker.com/r/philippbosch/python-slack-webhook-cli/

May I ask why a _Dockerfile_ like this wouldn't work for you?

```dockerfile
FROM python:3
RUN pip install slack-webhook-cli
```

**Comment by markv** [comment]
Thanks! It's working, the only other thing I would suggest is to create an automated build on dockerhub and link it to github so it can be updated when this project is updated.

I'm trying to use it in my CI as a notification stage, so I don't want to include it as a dockerfile in my project.

**Comment by philippbosch** [comment]
> create an automated build on dockerhub and link it to github

How to do that? Any pointers?

**Comment by philippbosch** [comment]
Ok, I found the docs. Reading through them now.

**Comment by philippbosch** [comment]
@markv Please use this image: https://hub.docker.com/r/philippbosch/slack-webhook-cli/
It looks like it needs to have the same name on GitHub and Docker Hub so I had to get rid of the `python-` prefix.

**Comment by markv** [comment]
Thanks, great work 💯🙏
