### ISSUE TITLE
Docker Hub image empty

### ISSUE THREAD

**Issue by markv** [philippbosch/slack-webhook-cli#4]
@philippbosch - I've tried to pull the docker image down today and I'm getting this error:
```
$docker pull philippbosch/slack-webhook-cli
Using default tag: latest
Error response from daemon: manifest for philippbosch/slack-webhook-cli:latest not found
```

If you look [here](https://hub.docker.com/r/philippbosch/slack-webhook-cli/builds/) it shows no builds.

It looks like the build may be broken because there is no dockerfile in this repo, you may also have to turn on the docker integration in the [github project settings](https://docs.docker.com/docker-hub/builds/#create-an-automated-build)

**Comment by philippbosch** [comment]
Oops, I seem to have forgotten to push it to Github. Thanks for the fix! 🙌
