### ISSUE TITLE
Insert other properties into attachments payload

### ISSUE THREAD

**Issue by colindean** [philippbosch/slack-webhook-cli#7]
I'd love to be able to set the [other properties](https://api.slack.com/docs/message-attachments) or to be able to construct my own JSON payload outside of slack-webhook-cli and pass it in.

**Comment by philippbosch** [comment]
I want to understand better. Are there any specific properties you are missing?

I feel like if you want to be able to construct and provide your own JSON payload, you could as well use _curl_. This tool‘s purpose as I see it is mainly to construct the JSON for you.

**Comment by colindean** [comment]
I’d like to be able to add multiple fields, add a title link, etc.

I came to the conclusion of using curl, too. It looks like it’ll be a little easier for my use case anyway because it will remove a dependency on python from my little app.
